### ISSUE TITLE
I want to use your project as my portfolio

### ISSUE THREAD

**Issue by VuongKha** [AkashJana18/portfolio#2]
Like the title, I'm asking to use this project as my portfolio. Your Portfolio was really awesome, it is the best gorgeous portfolio I have ever seen. Modern UI, cool painter, everything look good. Can I use your project?

**Comment by AkashJana18** [comment]
Thanks for the appreciation @VuongKha
Yes, you can use it.

**Comment by VuongKha** [comment]
Thank you, bro
